CREATE DATABASE DB_RPGS;

USE DB_RPGS;

CREATE TABLE TB_CLASSE(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
ARMA VARCHAR(255),
DESCRICAO VARCHAR (1000),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGEM(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
RACA VARCHAR(255),
ATAQUE DOUBLE,
DEFESA DOUBLE,
HP INT, 
PRIMARY KEY(ID),
CLASSE_ID BIGINT,
FOREIGN KEY(CLASSE_ID) REFERENCES TB_CLASSE(ID)
);

SELECT * FROM TB_CLASSE;
SELECT * FROM TB_PERSONAGEM;

INSERT INTO TB_CLASSE (NOME, ARMA, DESCRICAO) VALUES('ladrao','adaga','rouba');
INSERT INTO TB_CLASSE (NOME, ARMA, DESCRICAO) VALUES('mago','cajado','solta magia');
INSERT INTO TB_CLASSE (NOME, ARMA, DESCRICAO) VALUES('paladino','marreta','tudo pela fé');

INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES('vagner','humano', 2000, 700, 1000, 2 );
INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES('bruna','maga', 3000, 500, 1000, 3);
INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES('cinthia','guerreira', 2300, 3000, 1000, 2);





